name: whereisip
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - pip
  - numpy
  - pyproj
  - geocoder
  - country_converter
  - appdirs
  - pip:
      - -e .  # install git checkout of demo-dsproject in editable mode
      - latloncalc
